### ISSUE TITLE
Error install requeriments

### ISSUE THREAD

**Issue by jesusferm** [gowthamand/django-crud-ajax-login-register-fileupload#13]
I have this error after try install requeriments: pip3 install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Collecting asn1crypto==0.24.0
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
Collecting beautifulsoup4==4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting dj-database-url==0.5.0
  Using cached dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting Django==3.0.7
  Using cached Django-3.0.7-py3-none-any.whl (7.5 MB)
Collecting django-heroku==0.3.1
  Using cached django_heroku-0.3.1-py2.py3-none-any.whl (6.2 kB)
Collecting django-widget-tweaks==1.4.3
  Using cached django_widget_tweaks-1.4.3-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: gunicorn==20.0.4 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (20.0.4)
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.8.6-cp39-cp39-manylinux1_x86_64.whl (3.0 MB)
Collecting httplib2==0.18.0
  Using cached httplib2-0.18.0-py3-none-any.whl (95 kB)
Collecting idna==2.6
  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
Collecting keyring==10.6.0
  Using cached keyring-10.6.0-py2.py3-none-any.whl (38 kB)
Collecting keyrings.alt==3.0
  Using cached keyrings.alt-3.0-py2.py3-none-any.whl (21 kB)
Collecting launchpadlib==1.10.6
  Using cached launchpadlib-1.10.6.tar.gz (58 kB)
Collecting lazr.restfulclient==0.13.5
  Using cached lazr.restfulclient-0.13.5.tar.gz (58 kB)
Collecting lazr.uri==1.0.3
  Using cached lazr.uri-1.0.3.tar.gz (18 kB)
Collecting linecache2==1.0.0
  Using cached linecache2-1.0.0-py2.py3-none-any.whl (12 kB)
Collecting macaroonbakery==1.1.3
  Using cached macaroonbakery-1.1.3.tar.gz (78 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l1sdm6dj/macaroonbakery/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l1sdm6dj/macaroonbakery/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-squzhwnm
         cwd: /tmp/pip-install-l1sdm6dj/macaroonbakery/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l1sdm6dj/macaroonbakery/setup.py", line 40, in <module>
        distribution = platform.dist()
    AttributeError: module 'platform' has no attribute 'dist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

_______________________________________________________

I use, Fedora 33, x86_64, python 3.9, but installed 3.5

**Comment by saadgit** [comment]
Yes. same error.

**Comment by gowthamand** [comment]
I hope the issue has been resolved. If you have any further queries, please feel free to contact me at **gowthaman.nkl1@gmail.com.**
