### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by rceoliveira** [gowthamand/django-crud-ajax-login-register-fileupload#27]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bmiu0fcn/macaroonbakery/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bmiu0fcn/macaroonbakery/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bmiu0fcn/macaroonbakery/pip-egg-info
         cwd: /tmp/pip-install-bmiu0fcn/macaroonbakery/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bmiu0fcn/macaroonbakery/setup.py", line 40, in <module>
        distribution = platform.dist()
    AttributeError: module 'platform' has no attribute 'dist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by saugatrajbhandari** [comment]
please expain problem in detail

**Comment by gowthamand** [comment]
I hope the issue has been resolved. If you have any further queries, please feel free to contact me at gowthaman.nkl1@gmail.com.
